### PR TITLE
Removed printf custom specifier (revert back musl compatibility)

### PR DESCRIPTION
**Pull request by UladzimirTrehubenka**

### CODE REVIEW

**Comment by shailesh33** [comment]
thank you for your hard work. I hate to see it go but it was my ignorance about other libraries.

**Comment by shailesh33** [comment]
is it easy for you to port to v0.5.9? v0.6 is straight forward

**Comment by UladzimirTrehubenka** [comment]
I can port it if you want - could you provide git commit to port to?

**Comment by shailesh33** [comment]
it will be the latest of v0.5.9 branch.

**Comment by UladzimirTrehubenka** [comment]
Ok

**Pull request merged**
