### PR TITLE
configure.ac: stray merge artifact

### PR DESCRIPTION
**Pull request by proger**
Lol'd it has zero effect on the build process :)

### CODE REVIEW

**Comment by ipapapa** [comment]
@proger thanks for looking at it. see my response #213

**Comment by proger** [comment]
Thanks! Is it intentional that the branch currently worked on isn't default on GH though?

**Comment by ipapapa** [comment]
@proger Great question. Initially it made sense as we do not use that much the dev branch. Since we have moved to Gitflow workflow, we will default to "dev" branch.

**Comment by proger** [comment]
@ipapapa awesome!

**Comment by ipapapa** [comment]
@proger added docs #215 to get in the next release.

**Comment by proger** [comment]
Thanks!

**Pull request closed without merging**
