### PR TITLE
OpenSSL 1.1 compatibility

### PR DESCRIPTION
**Pull request by i-rinat**
OpenSSL 1.1 makes EVP_CIPHER_CTX an opaque struct, so a special function call is needed to allocate it. Library initialization was simplified a bit.

### CODE REVIEW

**Comment by i-rinat** [comment]
Related OpenSSL documentation pages:
* https://www.openssl.org/docs/man1.1.0/crypto/OpenSSL_add_all_algorithms.html
* https://www.openssl.org/docs/man1.1.0/crypto/EVP_EncryptInit.html

**Comment by i-rinat** [comment]
(Github interface said that the branch is not up-to-date, so I rebased it on top of the current `dev` state. No other changes were made.)

**Comment by i-rinat** [comment]
ping

**Comment by shailesh33** [comment]
Looks good to me.

**Comment by shailesh33** [comment]
@i-rinat I assume the two versions interoperate. In the sense that one node with older version can talk to a node with a newer version and vice versa,

**Comment by i-rinat** [comment]
> In the sense that one node with older version can talk to a node with a newer version and vice versa,

I didn't check that, but I guess there should be no differences in the actual algorithms. Otherwise newer versions of cURL would fail to talk to older HTTPS severs, for example.

**Pull request merged**
