### PR TITLE
Unnest core initialization functions and add extra error checking

### PR DESCRIPTION
**Pull request by smukil**
The core_start() function intializes everything required for dynomite
to be setup correctly. However, the code had nested all the functions
within core_ctx_create(), which recursively initialized unrelated
structures.

This patch unnests the entire chain which allows for better readability
and it also adds some extra error checking to avoid segfaults when
we fail to allocate memory, etc.

### CODE REVIEW

**Comment by shailesh33** [comment]
ok ok. I agree nesting is not the best of the thing but the general idea is to have a chain of initializers and deinitializers which at any given failure will unwind and uninitialize as it goes. Is there a specific order in which deinit should happen?

**Comment by smukil** [comment]
> ok ok. I agree nesting is not the best of the thing but the general idea is to have a chain of initializers and deinitializers which at any given failure will unwind and uninitialize as it goes. Is there a specific order in which deinit should happen?

Thanks for taking a look! Yes, I agree with that. I've made sure to de-initialize in the reverse order as the initialization is done. The "error:" label also has a comment stating the same under it.

Also, I've checked that we won't be accessing any invalid or uninitialized struct/variable if an error is hit early on in the initialization chain.

**Comment by shailesh33** [comment]
> > ok ok. I agree nesting is not the best of the thing but the general idea is to have a chain of initializers and deinitializers which at any given failure will unwind and uninitialize as it goes. Is there a specific order in which deinit should happen?
> 
> Thanks for taking a look! Yes, I agree with that. I've made sure to de-initialize in the reverse order as the initialization is done. The "error:" label also has a comment stating the same under it.
> 
> Also, I've checked that we won't be accessing any invalid or uninitialized struct/variable if an error is hit early on in the initialization chain.

It will be good if we can do this is such a way that it doesnt depend on developer to do the right thing. May be a table of init and deinit functions. Just a thought.
The PR per se looks good to me. Feel free to merge if you do not want to take it that far.

**Comment by smukil** [comment]
Thanks for the suggestion @shailesh33. That seems like a good idea. To go a bit further, if we're able to establish a hierarchy of structures each with its own setup() and destroy() functions (similar to constructors/destructors in C++), when anything goes wrong, we can call the top level struct's destroy() function, which would recursively destroy all the initialized nested structs. (The top-level struct will basically be the table of structs to init as you mentioned.)

That way, the onus isn't on the developer to do the right thing, and the code will be simpler to understand.

This is a much larger change though, but I think we can do it in stages.

**Comment by shailesh33** [comment]
> Thanks for the suggestion @shailesh33. That seems like a good idea. To go a bit further, if we're able to establish a hierarchy of structures each with its own setup() and destroy() functions (similar to constructors/destructors in C++), when anything goes wrong, we can call the top level struct's destroy() function, which would recursively destroy all the initialized nested structs. (The top-level struct will basically be the table of structs to init as you mentioned.)

They need not be nested structures. They can be components in the system which depend/use each other for example deinit msg and mbuf should be last. 
I agree its a larger change. Go ahead and merge this PR.

**Review by shailesh33 — APPROVED** [review]

**Comment by smukil** [comment]
@shailesh33 You're right, that's what I meant. I didn't mean to imply that all the structs need to be nested under a top level struct, but more like structs can refer to other structs, etc. Thanks for the review!

**Pull request merged**
