### PR TITLE
DNS seed provider

### PR DESCRIPTION
**Pull request by vseryakov**
Hi, this is a simple DNS provider, keeps seeds in a TXT record and keeps polling similar to the Florida provider. The PR also includes changes to compile for Mac OS X, handy for development purposes.

### CODE REVIEW

**Comment by shailesh33** [comment]
Would you be able to publish sample dns entries that you have?

**Comment by vseryakov** [comment]
screen shot 2016-02-24 at 6 36 10 pm

**Comment by shailesh33** [comment]
THe changes look good. I am concerned about the merge conflicts and also why does your pull request shows changes that are already there in the dev branch.

**Comment by vseryakov** [comment]
it was my working branch i started some time ago and kept merging, right now it is up to date with the dev branch showing only actual changes, the history is in my repo only for historic purposes if this is ok.

**Comment by shailesh33** [comment]
You should try to rebase instead of merge.  I see merge conflicts in the
pull requests.

**Comment by vseryakov** [comment]
done

**Comment by shailesh33** [comment]
Merged it manully/

**Pull request merged**
